using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using XamlX.Ast;
using XamlX.Emit;
using XamlX.IL;
using XamlX.Parsers;
using XamlX.Transform;
using XamlX.Transform.Transformers;
using XamlX.TypeSystem;


namespace Robust.Client.XamlUI
{
    [Generator]
    public class XamlUiPartialClassGenerator : ISourceGenerator
    {
        private const string AttributeName = "GenerateTypedNameReferencesAttribute";
        private const string AttributeFile = "GenerateTypedNameReferencesAttribute";
        private const string AttributeCode = @"// <auto-generated />
using System;
[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public sealed class GenerateTypedNameReferencesAttribute : Attribute { }
";

        class NameVisitor : IXamlAstVisitor
        {
            private List<(string name, string type)> _names = new List<(string name, string type)>();

            public static List<(string name, string type)> GetNames(IXamlAstNode node)
            {
                var visitor = new NameVisitor();
                node.Visit(visitor);
                return visitor._names;
            }

            private bool IsControl(IXamlType type) => type.FullName != "System.Object" &&
                                                      (type.FullName == "Robust.Client.UserInterface.Control" ||
                                                       IsControl(type.BaseType));

            public IXamlAstNode Visit(IXamlAstNode node)
            {
                if (node is XamlAstObjectNode objectNode)
                {
                    var clrtype = objectNode.Type.GetClrType();
                    var isControl = IsControl(clrtype);
                        //clrtype.Interfaces.Any(i =>
                        //i.IsInterface && i.FullName == "Robust.Client.UserInterface.IControl");

                    if (!isControl)
                        return node;

                    foreach (var child in objectNode.Children)
                    {
                        if (child is XamlAstXamlPropertyValueNode propertyValueNode &&
                            propertyValueNode.Property is XamlAstNamePropertyReference namedProperty &&
                            namedProperty.Name == "Name" &&
                            propertyValueNode.Values.Count > 0 &&
                            propertyValueNode.Values[0] is XamlAstTextNode text)
                        {
                            var reg = (text.Text, $@"{clrtype.Namespace}.{clrtype.Name}");
                            if (!_names.Contains(reg))
                            {
                                _names.Add(reg);
                            }
                        }
                    }
                }

                return node;
            }

            public void Push(IXamlAstNode node) { }

            public void Pop() { }
        }

        private static string GenerateSourceCode(
            INamedTypeSymbol classSymbol,
            string xamlFile,
            CSharpCompilation comp)
        {
            var className = classSymbol.Name;
            var nameSpace = classSymbol.ContainingNamespace.ToDisplayString();
            var parsed = XDocumentXamlParser.Parse(xamlFile);
            var typeSystem = new RoslynTypeSystem(comp);
            var compiler =
                new XamlILCompiler(
                    new TransformerConfiguration(typeSystem, typeSystem.Assemblies[0],
                        new XamlLanguageTypeMappings(typeSystem)),
                    new XamlLanguageEmitMappings<IXamlILEmitter, XamlILNodeEmitResult>(), false);
            compiler.Transformers.Add(new TypeReferenceResolver());
            compiler.Transform(parsed);
            var initialRoot = (XamlAstObjectNode) parsed.Root;
            var names = NameVisitor.GetNames(initialRoot);
            //var names = NameVisitor.GetNames((XamlAstObjectNode)XDocumentXamlParser.Parse(xamlFile).Root);
            var namedControls = names.Select(info => "        " +
                                $"internal global::{info.type} {info.name} => " +
                                $"this.FindControl<global::{info.type}>(\"{info.name}\");");
            return $@"// <auto-generated />
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
namespace {nameSpace}
{{
    partial class {className}
    {{
{string.Join("\n", namedControls)}
    }}
}}
";
        }


        public void Execute(GeneratorExecutionContext context)
        {
            context.AddSource(AttributeFile, SourceText.From(AttributeCode, Encoding.UTF8));
            if (!(context.SyntaxReceiver is NameReferenceSyntaxReceiver receiver))
            {
                return;
            }
            //Debugger.Launch();

            var comp = (CSharpCompilation) context.Compilation;
            var symbols = UnpackAnnotatedTypes(context, comp, receiver);
            if(symbols == null)
                return;

            foreach (var typeSymbol in symbols)
            {
                var xamlFileName = $"{typeSymbol.Name}.xaml";
                var relevantXamlFile = context.AdditionalFiles.FirstOrDefault(t => t.Path.EndsWith(xamlFileName));

                if (relevantXamlFile == null)
                {
                    context.ReportDiagnostic(
                        Diagnostic.Create(
                            new DiagnosticDescriptor(
                                "RXN0001",
                                "Unable to discover the relevant Robust XAML file.",
                                "Unable to discover the relevant Robust XAML file " +
                                $"expected at {xamlFileName}",
                                "Usage",
                                DiagnosticSeverity.Error,
                                true),
                            Location.None));
                    return;
                }

                var txt = relevantXamlFile.GetText()?.ToString();
                if (txt == null)
                {
                    context.ReportDiagnostic(
                        Diagnostic.Create(
                            new DiagnosticDescriptor(
                                "RXN0002",
                                $"Unexpected empty Xaml-File was found at {xamlFileName}",
                                "Expected Content due to a Class with the same name being annotated with [GenerateTypedNameReferences].",
                                "Usage",
                                DiagnosticSeverity.Error,
                                true),
                            Location.None));
                    return;
                }

                try
                {
                    var sourceCode = GenerateSourceCode(typeSymbol, txt, comp);
                    context.AddSource($"{typeSymbol.Name}.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
                }
                catch (Exception e)
                {
                    context.ReportDiagnostic(
                        Diagnostic.Create(
                            new DiagnosticDescriptor(
                                "AXN0003",
                                "Unhandled exception occured while generating typed Name references.",
                                $"Unhandled exception occured while generating typed Name references: {e}",
                                "Usage",
                                DiagnosticSeverity.Error,
                                true),
                            Location.None));
                    return;
                }
            }

            /*foreach (var additionalFile in context.AdditionalFiles)
            {
                if(!additionalFile.Path.EndsWith(".xaml")) continue;

                var txt = additionalFile.GetText()?.ToString();
                if(txt == null) continue; //TODO maybe log something here, i dunno

                var sourceCode = GenerateSourceCode(, txt);

                var parsed = XDocumentXamlParser.Parse(txt);
                var initialRoot = (XamlAstObjectNode) parsed.Root;
                var names = NameVisitor.GetNames(initialRoot);

                var classDirective = initialRoot.Children.OfType<XamlAstXmlDirective>()
                    .FirstOrDefault(d => d.Namespace == XamlNamespaces.Xaml2006 && d.Name == "Class");
                string classname;
                if (classDirective != null && classDirective.Values[0] is XamlAstTextNode tn)
                {
                    classname = tn.Text;
                }
                else
                {
                    classname = additionalFile.Path.Replace(".xaml","");
                }

                var classname_split = classname.Split('.');
                var @namespace = classname_split.Take(classname_split.Length - 2);
                var @class = classname_split[classname_split.Length-1];

                StringBuilder sourceBuilder = new StringBuilder($@"
                    using System;
                    namespace {@namespace}
                    {{
                        public static class {@class}
                        {{
                    ");

                foreach (var name in names)
                {
                    sourceBuilder.AppendLine($@"public {name.Type} {name.Name} => FindControl(""{name.Name}"");");
                }

                context.AddSource("helloWorldGenerated", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
            }*/

            // begin creating the source we'll inject into the users compilation
            /*StringBuilder sourceBuilder = new StringBuilder(@"
namespace HelloWorldGenerated
{
    public static class HelloWorld
    {
");
            foreach (var additionalFile in context.AdditionalFiles)
            {
                if (additionalFile.Path.EndsWith(".xaml"))
                {
                    var lines = additionalFile.GetText()?.Lines;
                    foreach (var line in lines)
                    {
                        var txt = line.ToString();
                        if(txt.Length != 0)
                            sourceBuilder.AppendLine($@"public static void {txt}(){{ Console.WriteLine(""yes"");}}");
                    }
                }
            }

            // finish creating the source to inject
            sourceBuilder.Append(@"
    }
}");

            // inject the created source into the users compilation
            context.AddSource("helloWorldGenerated", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));*/
        }

        private IReadOnlyList<INamedTypeSymbol> UnpackAnnotatedTypes(in GeneratorExecutionContext context, CSharpCompilation comp, NameReferenceSyntaxReceiver receiver)
        {
            var options = (CSharpParseOptions) comp.SyntaxTrees[0].Options;
            var compilation =
                comp.AddSyntaxTrees(CSharpSyntaxTree.ParseText(SourceText.From(AttributeCode, Encoding.UTF8), options));
            var symbols = new List<INamedTypeSymbol>();
            var attributeSymbol = compilation.GetTypeByMetadataName(AttributeName);
            foreach (var candidateClass in receiver.CandidateClasses)
            {
                var model = compilation.GetSemanticModel(candidateClass.SyntaxTree);
                var typeSymbol = (INamedTypeSymbol) model.GetDeclaredSymbol(candidateClass);
                var relevantAttribute = typeSymbol.GetAttributes().FirstOrDefault(attr =>
                    attr.AttributeClass != null &&
                    attr.AttributeClass.Equals(attributeSymbol, SymbolEqualityComparer.Default));

                if (relevantAttribute == null)
                {
                    continue;
                }

                var isPartial = candidateClass.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword));

                if (isPartial)
                {
                    symbols.Add(typeSymbol);
                }
                else
                {
                    var missingPartialKeywordMessage =
                        $"The type {typeSymbol.Name} should be declared with the 'partial' keyword " +
                        "as it is annotated with the [GenerateTypedNameReferences] attribute.";

                    context.ReportDiagnostic(
                        Diagnostic.Create(
                            new DiagnosticDescriptor(
                                "RXN0004",
                                missingPartialKeywordMessage,
                                missingPartialKeywordMessage,
                                "Usage",
                                DiagnosticSeverity.Error,
                                true),
                            Location.None));
                    return null;
                }
            }

            return symbols;
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new NameReferenceSyntaxReceiver());
        }
    }
}
