using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Robust.Client.MapEditor.Interface.Panels;

[GenerateTypedNameReferences]
internal sealed partial class EntityPickerButton : Control
{
    public EntityPickerButton(EntityPrototype prototype)
    {
        RobustXamlLoader.Load(this);

        PrototypeView.SetPrototype(prototype);

        PrototypeName.SetMessage(FormatName(prototype));
    }

    public static FormattedMessage FormatName(EntityPrototype prototype)
    {
        var msg = new FormattedMessage();

        string name;
        if (string.IsNullOrWhiteSpace(prototype.Name))
            name = prototype.ID;
        else
            name = prototype.Name;

        msg.AddText(name);

        if (!string.IsNullOrWhiteSpace(prototype.EditorSuffix))
            msg.AddMarkupOrThrow($@" [color=gray]\[{FormattedMessage.EscapeText(prototype.EditorSuffix)}\]");

        return msg;
    }
}
