using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Robust.Client.AutoGenerated;
using Robust.Client.Editor.Interface;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Robust.Client.MapEditor.Interface.Panels;

[GenerateTypedNameReferences]
internal sealed partial class EntityPickerPanel : EditorPanel
{
    private readonly ObservableCollection<EntityPrototype> _entities = [];

    [Dependency] private readonly IPrototypeManager _prototypeManager = null!;

    public EntityPickerPanel()
    {
        IoCManager.InjectDependencies(this);

        RobustXamlLoader.Load(this);

        PrototypeList.ItemsSource = _entities;
        PrototypeList.ItemTemplate = new ControlTemplateDelegate(CreateItem);

        Title = "Entities";

        UpdateList();
    }

    private void UpdateList()
    {
        var list = new List<EntityPrototype>();

        foreach (var prototype in _prototypeManager.EnumeratePrototypes<EntityPrototype>())
        {
            if (prototype.Abstract || prototype.HideSpawnMenu)
                continue;

            list.Add(prototype);
        }

        list.Sort((a, b) =>
        {
            var nameCmp = string.Compare(a.Name, b.Name, StringComparison.Ordinal);
            if (nameCmp != 0)
                return nameCmp;

            return string.Compare(a.EditorSuffix, b.EditorSuffix, StringComparison.Ordinal);
        });

        _entities.Clear();
        _entities.AddRange(list);
    }

    private Control CreateItem(object? arg)
    {
        return new EntityPickerButton((EntityPrototype)arg!);
    }
}
