using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Robust.Client.MapEditor.Interface.Panels;

[GenerateTypedNameReferences]
internal sealed partial class EntityPickerButton : Control
{
    public EntityPickerButton(EntityPrototype prototype)
    {
        RobustXamlLoader.Load(this);

        PrototypeView.SetPrototype(prototype);
        if (string.IsNullOrWhiteSpace(prototype.Name))
            PrototypeName.Text = prototype.ID;
        else
            PrototypeName.Text = prototype.Name;

        if (!string.IsNullOrWhiteSpace(prototype.EditorSuffix))
            PrototypeName.Text +=  $" [{prototype.EditorSuffix}]";
    }
}
