using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Editor.Interface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Log;
using Robust.Shared.MapEditor;

namespace Robust.Client.MapEditor.Interface.Panels;

[GenerateTypedNameReferences]
internal sealed partial class MapEditorViewportPanel : EditorPanel
{
    private readonly ISawmill _sawmill;
    private readonly IEntityManager _entityManager;
    private readonly ClientMapEditorSystem _mapEditor;
    private readonly EntityUid _mapData;

    private MapEditorMessages.ActionId _eyeAction;
    private Entity<MapEditorEyeComponent> _eyeEntity;

    public MapEditorViewportPanel(
        ISawmill sawmill,
        IEntityManager entityManager,
        ClientMapEditorSystem mapEditor,
        EntityUid mapData)
    {
        _sawmill = sawmill;
        _entityManager = entityManager;
        _mapEditor = mapEditor;
        _mapData = mapData;

        RobustXamlLoader.Load(this);
        Title = "Viewport";

        Viewport.WorldPosChanged += ViewportOnWorldPosChanged;

        CreateViewer();
    }

    public void Shutdown()
    {
        _mapEditor.EyeCreated -= MapEditorOnEyeCreated;
    }

    private void CreateViewer()
    {
        _eyeAction = MapEditorMessages.ActionId.Create();

        _mapEditor.EyeCreated += MapEditorOnEyeCreated;
        _mapEditor.RequestCreateView(_mapData, default, _eyeAction);
    }

    private void MapEditorOnEyeCreated(Entity<MapEditorEyeComponent> ent)
    {
        if (ent.Comp.Action != _eyeAction)
            return;

        _sawmill.Debug($"Received eye for viewport: {_entityManager.ToPrettyString(ent)}");

        _mapEditor.EyeCreated -= MapEditorOnEyeCreated;
        _eyeEntity = ent;

        Viewport.Eye = _entityManager.GetComponent<EyeComponent>(ent).Eye;
    }

    private void ViewportOnWorldPosChanged(Vector2 newWorldPos)
    {
        _mapEditor.EyeMoveTo(_eyeEntity, newWorldPos);
    }
}
