using Robust.Client.AutoGenerated;
using Robust.Client.Editor.Interface;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.MapEditor.Interface.Panels;

[GenerateTypedNameReferences]
public sealed partial class MapEditorOutlinerPanel : EditorPanel
{
    public MapEditorOutlinerPanel()
    {
        RobustXamlLoader.Load(this);

        Title = "Outliner";
    }
}
