using Robust.Client.AutoGenerated;
using Robust.Client.Editor.Interface;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.MapEditor.Interface.Panels;

[GenerateTypedNameReferences]
public sealed partial class MapEditorInspectorPanel : EditorPanel
{
    public MapEditorInspectorPanel()
    {
        RobustXamlLoader.Load(this);

        Title = "Inspector";
    }
}
