using Robust.Client.AutoGenerated;
using Robust.Client.Editor.Interface;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.MapEditor.Interface.Panels;

[GenerateTypedNameReferences]
internal sealed partial class MapEditorViewPanel : EditorPanel
{
    public MapEditorViewPanel()
    {
        RobustXamlLoader.Load(this);
        Title = "Viewport";
    }
}
