using System;

namespace Robust.Shared.Analyzers;

/// <summary>
///     Placed on auto-generated classes to mark to certain robust analyzers that they are auto-generated
///     and may need to be ignored (e.g. the access analyzer)
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Interface)]
public sealed class RobustAutoGeneratedAttribute : Attribute
{
}
