using System;

namespace Robust.Shared.Analyzers;

/// <summary>
///     Placed on auto-generated classes to mark to certain robust analyzers that they are auto-generated
///     and may need to be ignored (e.g. the access analyzer)
/// </summary>
/// <remarks>
///     Users should never use this attribute themselves, it silences a significant number of useful warnings and is
///     meant strictly for generated code.
/// </remarks>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Interface)]
public sealed class RobustAutoGeneratedAttribute : Attribute
{
}
