# Used internally by the THE() function.
zzzz-the = { PROPER($ent) ->
    *[false] a { $ent }
     [true] { $ent }
    }

# Used internally by the SUBJECT() function (autogenerated).
zzzz-subject-pronoun = { $gender ->
    [male] ele
    [female] ela
    [epicene] eles
    [neuter] ele
   *[other] { $gender }
   }

# Used internally by the OBJECT() function (autogenerated).
zzzz-object-pronoun = { $gender ->
    [male] ele
    [female] ela
    [epicene] eles
    [neuter] isso
   *[other] { $gender }
   }

# Used internally by the POSS-PRONOUN() function (autogenerated).
zzzz-possessive-pronoun = { $gender ->
    [male] dele
    [female] dela
    [epicene] deles
    [neuter] dele
   *[other] { $gender }
   }

# Used internally by the POSS-ADJ() function (autogenerated).
zzzz-possessive-adjective = { $gender ->
    [male] dele
    [female] dela
    [epicene] deles
    [neuter] dele
   *[other] { $gender }
   }

# Used internally by the REFLEXIVE() function (autogenerated).
zzzz-reflexive-pronoun = { $gender ->
    [male] ele mesmo
    [female] ela mesmo
    [epicene] eles mesmos
    [neuter] ele mesmo
   *[other] { $gender }
   }

# Used internally by the CONJUGATE-BE() function (autogenerated).
zzzz-conjugate-be = { $gender ->
    [epicene] é
   *[other] é
   }

# Used internally by the CONJUGATE-HAVE() function (autogenerated).
zzzz-conjugate-have = { $gender ->
    [epicene] tenho
   *[other] tem
   }

# Used internally by the CONJUGATE-BASIC() function.
zzzz-conjugate-basic = { $gender ->
    [epicene] { $first }
   *[other] { $second }
   }
