using System;
using System.Collections.Generic;
using Robust.Shared.Enums;
using Robust.Shared.GameStates;
using Robust.Shared.IoC;
using Robust.Shared.Serialization.Manager.Attributes;
using Robust.Shared.ViewVariables;
using Robust.Shared.Prototypes;
using Robust.Shared.Localization;

namespace Robust.Shared.GameObjects.Components.Localization;

/// <summary>
///     Overrides grammar attributes specified in prototypes or localization files.
/// </summary>
[RegisterComponent, NetworkedComponent, AutoGenerateComponentState]
// [Access(typeof(GrammarSystem))] TODO access
public sealed partial class GrammarComponent : Component
{
    [DataField, AutoNetworkedField]
    public Dictionary<string, string> Attributes = new();

    [ViewVariables]
    public Gender? Gender
    {
        get => Attributes.TryGetValue("gender", out var g) ? Enum.Parse<Gender>(g, true) : null;
        [Obsolete("Use GrammarSystem.SetGender instead")]
        set => IoCManager.Resolve<IEntityManager>().System<GrammarSystem>().SetGender((Owner, this), value);
    }

    /// <summary>
    ///     Optional list of custom pronouns for an entity, as well as the tense they belong to.
    ///     If this list does not contain a pronoun for a desired tense,
    ///     the gender's pronoun will be used as a fallback.
    /// </summary>
    [DataField, AutoNetworkedField]
    public Dictionary<ProtoId<PronounTensePrototype>, string> Pronouns = [];

    [ViewVariables]
    public bool? ProperNoun
    {
        get => Attributes.TryGetValue("proper", out var g) ? bool.Parse(g) : null;
        [Obsolete("Use GrammarSystem.SetProperNoun instead")]
        set => IoCManager.Resolve<IEntityManager>().System<GrammarSystem>().SetProperNoun((Owner, this), value);
    }
}

[Prototype]
public sealed partial class PronounTensePrototype : IPrototype
{
    [IdDataField]
    public string ID { get; private set; } = default!;

    /// <summary>
    ///     String used in FTL to denote a CTX function (all caps).
    ///     CTX functions will be autogenerated by the engine if this is provided.
    /// </summary>
    [DataField]
    public string? FtlFunction { get; private set; }

    /// <summary>
    ///     Ftl string to return when provided with a default gender
    ///     (male, female, epicene, neuter).
    /// </summary>
    [DataField]
    public string? FtlReturn { get; private set; }

    /// <summary>
    ///     Locale string denoting name of this tense.
    /// </summary>
    [DataField]
    public LocId Name { get; private set; }

    /// <summary>
    ///     Locale string with a summary of this tense.
    /// </summary>
    [DataField]
    public LocId Description { get; private set; }

    private static readonly IPrototypeManager _protoMan = default!;
    public static ProtoId<PronounTensePrototype>? ParseFromDbString(string input)
    {
        if (_protoMan.TryIndex<PronounTensePrototype>(input, out var pronoun))
            return pronoun;
        return null;
    }
}
