#!/bin/bash

gitroot=`git rev-parse --show-toplevel`

cd "$gitroot/BuildChecker"

if [ -f "git_helper.py" ]
then
    if [[ `uname` == MINGW* || `uname` == CYGWIN* ]]; then
        # Windows
        # Can't update hooks from here because we are a hook,
        # and the file is read only while it's used.
        # Thanks Windows.
        py -3 git_helper.py --quiet --nohooks
    else
        # Not Windows, so probably some other Unix thing.
        python3 git_helper.py --quiet
    fi
fi
