using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.UserInterface.CustomControls;

[GenerateTypedNameReferences]
internal sealed partial class DebugConsoleCompletion : Popup
{
    public DebugConsoleCompletion()
    {
        RobustXamlLoader.Load(this);
    }
}
