using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using Robust.Client.AutoGenerated;
using Robust.Client.Editor.Interface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Robust.Client.UserInterface.CustomControls
{
    /// <summary>
    ///     The default debug console that drops down from the top of the screen.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class DropDownDebugConsole : Control
    {
        private bool _targetVisible;
        private float _curAnchorOffset = -ScreenRatio;

        private int _focusStamp;
        private readonly Dictionary<IConsoleTab, int> _lastFocusTimes = new();

        public const float ScreenRatio = 0.35f;

        public DropDownDebugConsole()
        {
            RobustXamlLoader.Load(this);

            LayoutContainer.SetAnchorPreset(MainControl, LayoutContainer.LayoutPreset.TopWide);
            LayoutContainer.SetAnchorPreset(BelowConsole, LayoutContainer.LayoutPreset.TopWide);

            MainControl.PanelAdded += MainControlOnPanelAdded;
            MainControl.PanelRemoved += MainControlOnPanelRemoved;

            var consoleTab = new DebugConsoleTab
            {
                CanUndock = false,
                CanClose = false,
            };
            MainControl.AddPanel(consoleTab);
            _lastFocusTimes[consoleTab] = -1;
        }

        private void MainControlOnPanelAdded(EditorPanel obj)
        {
            if (obj is not IConsoleTab tab)
                return;

            tab.CommandBar.OnKeyBindDown += CommandBarPubOnOnKeyBindDown;
            tab.Focused += TabOnFocused;
        }

        private void MainControlOnPanelRemoved(EditorPanel obj)
        {
            if (obj is not IConsoleTab tab)
                return;

            tab.CommandBar.OnKeyBindDown -= CommandBarPubOnOnKeyBindDown;
            tab.Focused -= TabOnFocused;
            _lastFocusTimes.Remove(tab);
        }

        private void UpdateAnchorOffset()
        {
            LayoutContainer.SetAnchorBottom(MainControl, _curAnchorOffset+ScreenRatio);
            LayoutContainer.SetAnchorTop(MainControl, _curAnchorOffset);
            LayoutContainer.SetAnchorTop(BelowConsole, _curAnchorOffset+ScreenRatio);
        }

        private void CommandBarPubOnOnKeyBindDown(GUIBoundKeyEventArgs args)
        {
            if (args.Function == EngineKeyFunctions.ShowDebugConsole)
            {
                Toggle();
                args.Handle();
            }
            else if (args.Function == EngineKeyFunctions.TextReleaseFocus)
            {
                Toggle();
                args.Handle();
            }
        }

        private void TabOnFocused(IConsoleTab obj)
        {
            ref var lastFocused = ref CollectionsMarshal.GetValueRefOrAddDefault(_lastFocusTimes, obj, out _);
            lastFocused = _focusStamp;
            _focusStamp += 1;
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            if (!MainControl.Visible)
            {
                return;
            }

            var targetOffset = _targetVisible ? 0 : -ScreenRatio;

            if (MathHelper.CloseTo(targetOffset, _curAnchorOffset))
            {
                if (!_targetVisible)
                {
                    MainControl.Visible = false;
                }

                _curAnchorOffset = targetOffset;
            }
            else
            {
                _curAnchorOffset = UIAnimations.LerpAnimate(_curAnchorOffset, targetOffset, args.DeltaSeconds, 20);
            }

            UpdateAnchorOffset();
        }

        public void Toggle()
        {
            var bestBar = _lastFocusTimes.MaxBy(x => x.Value).Key.CommandBar;
            _targetVisible = !_targetVisible;
            if (_targetVisible)
            {
                MainControl.Visible = true;
                bestBar.IgnoreNext = true;
                bestBar.GrabKeyboardFocus();
            }
            else
            {
                bestBar.ReleaseKeyboardFocus();
            }
        }
    }
}
