using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;

namespace Robust.Client.UserInterface.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class EntitySpawnButton : Control
{
    public string PrototypeId => Prototype.ID;
    public EntityPrototype Prototype;
    public int Index;

    public EntitySpawnButton(EntityPrototype prototype, int index)
    {
        RobustXamlLoader.Load(this);

        Prototype = prototype;
        Index = index;

        var entityLabelText = string.IsNullOrEmpty(prototype.Name) ? prototype.ID : prototype.Name;

        if (!string.IsNullOrWhiteSpace(prototype.EditorSuffix))
        {
            entityLabelText += $" [{prototype.EditorSuffix}]";
        }

        EntityLabel.Text = entityLabelText;
        ActualButton.ToolTip = Loc.GetString("entity-spawn-window-tooltip-proto-title") + " " + prototype.ID
                               + (!string.IsNullOrEmpty(prototype.Description) ? "\n" + prototype.Description : string.Empty);

        EntityTextureRects.SetPrototype(prototype.ID);
    }
}
