using System;
using System.Numerics;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;
using Robust.Shared.Maths;

namespace Robust.Client.UserInterface.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class TileSpawnWindow : DefaultWindow
{
    private readonly Animation _variantAnimation;

    /// Set to true to advance the display of the tile variants.
    /// This is a bit of a hack; ideally we'd like to just call a method
    /// but there's no AnimationTrack which can do that.
    [Animatable]
    public bool UpdateVariantDisplay
    {
        set
        {
            if (value)
            {
                AdvanceVariantDisplay();
            }
        }
    }

    public TileSpawnWindow()
    {
        RobustXamlLoader.Load(this);

        const float animDuration = 1.0f;
        var track = new AnimationTrackControlProperty
        {
            Property = "UpdateVariantDisplay",
            KeyFrames = {
                new AnimationTrackProperty.KeyFrame(false, 0.0f),
                new AnimationTrackProperty.KeyFrame(true, animDuration)
            }
        };
        _variantAnimation = new Animation
        {
            AnimationTracks = { track },
            Length = TimeSpan.FromSeconds(animDuration)
        };

        const string variantAnimKey = "_variantAnimation";
        PlayAnimation(_variantAnimation, variantAnimKey);
        AnimationCompleted += (key) => PlayAnimation(_variantAnimation, variantAnimKey);
    }

    protected override void Opened()
    {
        base.Opened();

        SearchBar.GrabKeyboardFocus();
    }

    private void AdvanceVariantDisplay()
    {
        for (var i = 0; i < TileList.Count; i++)
        {
            var item = TileList[i];
            if (item.IconRegion.Size != Vector2.Zero && item.Icon != null)
            {
                var regionSize = item.IconRegion.Size;
                var nextLeft = item.IconRegion.Left + regionSize.X;
                if (nextLeft >= item.Icon.Width)
                {
                    nextLeft = 0;
                }
                item.IconRegion = UIBox2.FromDimensions(new Vector2(nextLeft, 0), regionSize);
            }
        }
    }
}
