<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\MSBuild\Robust.Engine.props" />
  <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" />
    <PackageReference Include="Microsoft.ILVerification" PrivateAssets="compile" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
    <PackageReference Include="Nett" PrivateAssets="compile" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.Numerics.Tensors" />
    <PackageReference Include="VorbisPizza" PrivateAssets="compile" />
    <PackageReference Include="Pidgin" />
    <PackageReference Include="prometheus-net" />
    <PackageReference Include="Robust.Shared.AuthLib" PrivateAssets="none" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="Microsoft.Win32.Registry" PrivateAssets="compile" />
    <PackageReference Include="Linguini.Bundle" />
    <PackageReference Include="SharpZstd.Interop" PrivateAssets="compile" ExcludeAssets="native" />
    <PackageReference Include="SpaceWizards.Sodium" PrivateAssets="compile" />
    <!-- Add libsodium to control version, SpaceWizards.Sodium's dependency is behind -->
    <PackageReference Include="libsodium" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="TerraFX.Interop.Windows" PrivateAssets="compile" />
    <PackageReference Include="Tracy-CSharp" />

    <!-- Needed to pin transitive dependency versions. -->
    <PackageReference Include="System.Reflection.Metadata" />

  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lidgren.Network\Lidgren.Network.csproj" />
    <ProjectReference Include="..\NetSerializer\NetSerializer\NetSerializer.csproj" />
    <ProjectReference Include="..\Robust.Shared.Maths\Robust.Shared.Maths.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Utility\TypeAbbreviations.yaml">
      <LogicalName>Robust.Shared.Utility.TypeAbbreviations.yaml</LogicalName>
    </EmbeddedResource>
    <None Remove="ContentPack\Sandbox.yml" />
    <EmbeddedResource Include="ContentPack\Sandbox.yml">
      <LogicalName>Robust.Shared.ContentPack.Sandbox.yml</LogicalName>
    </EmbeddedResource>
    <None Include="..\MSBuild\Robust.Serialization.Generator.targets" Pack="true" PackagePath="build\" />
    <None Include="..\MSBuild\Robust.CompNetworkGenerator.targets" Pack="true" PackagePath="build\" />
    <None Include="..\MSBuild\Robust.EntitySystemSubscriptionsGenerator.targets" Pack="true" PackagePath="build\" />
    <None Include="..\MSBuild\Robust.Analyzers.targets" Pack="true" PackagePath="build\" />
  </ItemGroup>

  <Target Name="PackAnalyzers" AfterTargets="Build">
    <Copy SourceFiles="..\Robust.Serialization.Generator\bin\Debug\netstandard2.0\Robust.Serialization.Generator.dll" DestinationFolder="analyzers\dotnet\cs\" Condition="Exists('..\Robust.Serialization.Generator\bin\Debug\netstandard2.0\Robust.Serialization.Generator.dll')" />
    <Copy SourceFiles="..\Robust.Serialization.Generator\bin\Release\netstandard2.0\Robust.Serialization.Generator.dll" DestinationFolder="analyzers\dotnet\cs\" Condition="Exists('..\Robust.Serialization.Generator\bin\Release\netstandard2.0\Robust.Serialization.Generator.dll')" />
    <Copy SourceFiles="..\Robust.Shared.CompNetworkGenerator\bin\Debug\netstandard2.0\Robust.Shared.CompNetworkGenerator.dll" DestinationFolder="analyzers\dotnet\cs\" Condition="Exists('..\Robust.Shared.CompNetworkGenerator\bin\Debug\netstandard2.0\Robust.Shared.CompNetworkGenerator.dll')" />
    <Copy SourceFiles="..\Robust.Shared.CompNetworkGenerator\bin\Release\netstandard2.0\Robust.Shared.CompNetworkGenerator.dll" DestinationFolder="analyzers\dotnet\cs\" Condition="Exists('..\Robust.Shared.CompNetworkGenerator\bin\Release\netstandard2.0\Robust.Shared.CompNetworkGenerator.dll')" />
    <Copy SourceFiles="..\Robust.Shared.EntitySystemSubscriptionsGenerator\bin\Debug\netstandard2.0\Robust.Shared.EntitySystemSubscriptionsGenerator.dll" DestinationFolder="analyzers\dotnet\cs\" Condition="Exists('..\Robust.Shared.EntitySystemSubscriptionsGenerator\bin\Debug\netstandard2.0\Robust.Shared.EntitySystemSubscriptionsGenerator.dll')" />
    <Copy SourceFiles="..\Robust.Shared.EntitySystemSubscriptionsGenerator\bin\Release\netstandard2.0\Robust.Shared.EntitySystemSubscriptionsGenerator.dll" DestinationFolder="analyzers\dotnet\cs\" Condition="Exists('..\Robust.Shared.EntitySystemSubscriptionsGenerator\bin\Release\netstandard2.0\Robust.Shared.EntitySystemSubscriptionsGenerator.dll')" />
    <Copy SourceFiles="..\Robust.Analyzers\bin\Debug\netstandard2.0\Robust.Analyzers.dll" DestinationFolder="analyzers\dotnet\cs\" Condition="Exists('..\Robust.Analyzers\bin\Debug\netstandard2.0\Robust.Analyzers.dll')" />
    <Copy SourceFiles="..\Robust.Analyzers\bin\Release\netstandard2.0\Robust.Analyzers.dll" DestinationFolder="analyzers\dotnet\cs\" Condition="Exists('..\Robust.Analyzers\bin\Release\netstandard2.0\Robust.Analyzers.dll')" />
  </Target>

  <ItemGroup>
    <None Include="analyzers\dotnet\cs\Robust.Serialization.Generator.dll" Pack="true" PackagePath="analyzers\dotnet\cs\" Visible="false" />
    <None Include="analyzers\dotnet\cs\Robust.Shared.CompNetworkGenerator.dll" Pack="true" PackagePath="analyzers\dotnet\cs\" Visible="false" />
    <None Include="analyzers\dotnet\cs\Robust.Shared.EntitySystemSubscriptionsGenerator.dll" Pack="true" PackagePath="analyzers\dotnet\cs\" Visible="false" />
    <None Include="analyzers\dotnet\cs\Robust.Analyzers.dll" Pack="true" PackagePath="analyzers\dotnet\cs\" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Input\CommandBindMapping.cs" />
    <Compile Update="Serialization\RobustMappedStringSerializer.MappedStringDict.cs">
      <DependentUpon>RobustMappedStringSerializer.cs</DependentUpon>
    </Compile>
    <Compile Update="Serialization\RobustSerializer.Handshake.cs">
      <DependentUpon>RobustSerializer.cs</DependentUpon>
    </Compile>
    <Compile Update="Serialization\RobustMappedStringSerializer.MappedStringDict.cs">
      <DependentUpon>RobustMappedStringSerializer.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <Import Project="..\MSBuild\Robust.Properties.targets" />
  <Import Project="..\MSBuild\Robust.CompNetworkGenerator.targets" />
  <Import Project="..\MSBuild\Robust.EntitySystemSubscriptionsGenerator.targets" />
</Project>
