extern alias SerializationGenerator;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;
using SerializationGenerator::Robust.Serialization.Generator;

namespace Robust.Analyzers.Tests;

[TestFixture]
[TestOf(typeof(EntityRelationsGenerator))]
[Parallelizable(ParallelScope.All)]
public sealed class EntityRelationsGeneratorTest
{
    private const string TypesCode = """
        global using System;
        global using Robust.Shared.Analyzers;
        global using Robust.Shared.GameObjects;

        namespace Robust.Shared.Analyzers
        {
            [AttributeUsage(AttributeTargets.Class, Inherited = false)]
            public sealed class AutoGenerateEntityRelationsAttribute : Attribute
            {
                public readonly bool Dirty;

                public readonly bool ShutdownEvent;

                public AutoGenerateEntityRelationsAttribute(bool dirty = false, bool shutdownEvent = true)
                {
                    Dirty = dirty;
                    ShutdownEvent = shutdownEvent;
                }
            }

            [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]
            public sealed class AutoRelationFieldAttribute : Attribute;
        }

        namespace Robust.Shared.GameObjects
        {
            public interface IComponent;

            public record struct EntityRelation;

            public readonly struct EntityUid;
        }
        """;

    private const string DefaultCollectionResult = """
    // <auto-generated />

    using Robust.Shared.GameObjects;

    public partial class FooComponent
    {
    [RobustAutoGenerated]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public sealed partial class FooComponent_AutoRelationsSystem : EntitySystem
    {
        public override void Initialize()
        {
            base.Initialize();
            SubscribeLocalEvent<FooComponent, ComponentShutdown>(OnRelationShutdown);
            SubscribeLocalEvent<FooComponent, EntityRelationDeleteEvent>(OnRelationDeleted);
        }

        private void OnRelationDeleted(Entity<FooComponent> ent, ref EntityRelationDeleteEvent args)
        {
            ent.Comp.Foo.Remove(args.Relation);

        }

        private void OnRelationShutdown(Entity<FooComponent> ent, ref ComponentShutdown args)
        {
            FooComponent.ClearComponentRelations(ent, EntityManager);
        }
    }

        /// <summary>
        /// Auto-generated method that clears all relations in a certain entity.
        /// This has to be called on component shutdown to keep all relations correct.
        /// </summary>
        public static void ClearComponentRelations(Entity<FooComponent> ent, IEntityManager entMan)
        {
            entMan.ClearRelation(ent.Owner, ent.Comp.Foo);

        }
    }

    """;

    [Test]
    public void TestBasic()
    {
        var result = RunGenerator("""
            [AutoGenerateEntityRelations]
            public sealed partial class FooComponent : IComponent
            {
                [AutoRelationField]
                public EntityRelation Foo;
            }
            """);

        ExpectNoDiagnostics(result);
        ExpectSource(
            result,
            """
            // <auto-generated />

            using Robust.Shared.GameObjects;

            public partial class FooComponent
            {
            [RobustAutoGenerated]
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            public sealed partial class FooComponent_AutoRelationsSystem : EntitySystem
            {
                public override void Initialize()
                {
                    base.Initialize();
                    SubscribeLocalEvent<FooComponent, ComponentShutdown>(OnRelationShutdown);
                    SubscribeLocalEvent<FooComponent, EntityRelationDeleteEvent>(OnRelationDeleted);
                }

                private void OnRelationDeleted(Entity<FooComponent> ent, ref EntityRelationDeleteEvent args)
                {
                    if (ent.Comp.Foo == args.Relation)
                        ent.Comp.Foo = EntityRelation.Null;

                }

                private void OnRelationShutdown(Entity<FooComponent> ent, ref ComponentShutdown args)
                {
                    FooComponent.ClearComponentRelations(ent, EntityManager);
                }
            }

                /// <summary>
                /// Auto-generated method that clears all relations in a certain entity.
                /// This has to be called on component shutdown to keep all relations correct.
                /// </summary>
                public static void ClearComponentRelations(Entity<FooComponent> ent, IEntityManager entMan)
                {
                    entMan.ClearRelation(ent.Owner, ref ent.Comp.Foo);

                }
            }

            """);
    }

    [Test]
    public void TestNullable()
    {
        var result = RunGenerator("""
            [AutoGenerateEntityRelations]
            public sealed partial class FooComponent : IComponent
            {
                [AutoRelationField]
                public EntityRelation? Foo;
            }
            """);

        ExpectNoDiagnostics(result);
        ExpectSource(
            result,
            """
            // <auto-generated />

            using Robust.Shared.GameObjects;

            public partial class FooComponent
            {
            [RobustAutoGenerated]
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            public sealed partial class FooComponent_AutoRelationsSystem : EntitySystem
            {
                public override void Initialize()
                {
                    base.Initialize();
                    SubscribeLocalEvent<FooComponent, ComponentShutdown>(OnRelationShutdown);
                    SubscribeLocalEvent<FooComponent, EntityRelationDeleteEvent>(OnRelationDeleted);
                }

                private void OnRelationDeleted(Entity<FooComponent> ent, ref EntityRelationDeleteEvent args)
                {
                    if (ent.Comp.Foo.HasValue && ent.Comp.Foo.Value == args.Relation)
                        ent.Comp.Foo = null;

                }

                private void OnRelationShutdown(Entity<FooComponent> ent, ref ComponentShutdown args)
                {
                    FooComponent.ClearComponentRelations(ent, EntityManager);
                }
            }

                /// <summary>
                /// Auto-generated method that clears all relations in a certain entity.
                /// This has to be called on component shutdown to keep all relations correct.
                /// </summary>
                public static void ClearComponentRelations(Entity<FooComponent> ent, IEntityManager entMan)
                {
                    entMan.ClearRelation(ent.Owner, ref ent.Comp.Foo);

                }
            }

            """);
    }

    [Test]
    public void TestList()
    {
        var result = RunGenerator("""
            [AutoGenerateEntityRelations]
            public sealed partial class FooComponent : IComponent
            {
                [AutoRelationField]
                public List<EntityRelation> Foo = new();
            }
            """);

        ExpectNoDiagnostics(result);
        ExpectSource(
            result,
            DefaultCollectionResult);
    }

    [Test]
    public void TestHashSet()
    {
        var result = RunGenerator("""
            [AutoGenerateEntityRelations]
            public sealed partial class FooComponent : IComponent
            {
                [AutoRelationField]
                public HashSet<EntityRelation> Foo = new();
            }
            """);

        ExpectNoDiagnostics(result);
        ExpectSource(
            result,
            DefaultCollectionResult);
    }

    [Test]
    public void TestDictionaryKey()
    {
        var result = RunGenerator("""
            [AutoGenerateEntityRelations]
            public sealed partial class FooComponent : IComponent
            {
                [AutoRelationField]
                public Dictionary<EntityRelation, int> Foo = new();
            }
            """);

        ExpectNoDiagnostics(result);
        ExpectSource(
            result,
            DefaultCollectionResult);
    }

    [Test]
    public void TestDictionaryValue()
    {
        var result = RunGenerator("""
            [AutoGenerateEntityRelations]
            public sealed partial class FooComponent : IComponent
            {
                [AutoRelationField]
                public Dictionary<int, EntityRelation> Foo = new();
            }
            """);

        ExpectNoDiagnostics(result);
        ExpectSource(
            result,
            """
            // <auto-generated />

            using Robust.Shared.GameObjects;

            public partial class FooComponent
            {
            [RobustAutoGenerated]
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            public sealed partial class FooComponent_AutoRelationsSystem : EntitySystem
            {
                public override void Initialize()
                {
                    base.Initialize();
                    SubscribeLocalEvent<FooComponent, ComponentShutdown>(OnRelationShutdown);
                    SubscribeLocalEvent<FooComponent, EntityRelationDeleteEvent>(OnRelationDeleted);
                }

                private void OnRelationDeleted(Entity<FooComponent> ent, ref EntityRelationDeleteEvent args)
                {
                    foreach (var (key, value) in ent.Comp.Foo)
                    {
                        if (value == args.Relation)
                            ent.Comp.Foo[key] = EntityRelation.Null;
                    }

                }

                private void OnRelationShutdown(Entity<FooComponent> ent, ref ComponentShutdown args)
                {
                    FooComponent.ClearComponentRelations(ent, EntityManager);
                }
            }

                /// <summary>
                /// Auto-generated method that clears all relations in a certain entity.
                /// This has to be called on component shutdown to keep all relations correct.
                /// </summary>
                public static void ClearComponentRelations(Entity<FooComponent> ent, IEntityManager entMan)
                {
                    entMan.ClearRelation(ent.Owner, ent.Comp.Foo);

                }
            }

            """);
    }

    [Test]
    public void TestAutoState()
    {
        var result = RunGenerator("""
            [AutoGenerateEntityRelations]
            public sealed partial class FooComponent : IComponent
            {
                [AutoRelationField, AutoNetworkedField]
                public EntityRelation Foo;
            }
            """);

        ExpectNoDiagnostics(result);
        ExpectSource(
            result,
            """
            // <auto-generated />

            using Robust.Shared.GameObjects;

            public partial class FooComponent
            {
            [RobustAutoGenerated]
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            public sealed partial class FooComponent_AutoRelationsSystem : EntitySystem
            {
                public override void Initialize()
                {
                    base.Initialize();
                    SubscribeLocalEvent<FooComponent, ComponentShutdown>(OnRelationShutdown);
                    SubscribeLocalEvent<FooComponent, EntityRelationDeleteEvent>(OnRelationDeleted);
                }

                private void OnRelationDeleted(Entity<FooComponent> ent, ref EntityRelationDeleteEvent args)
                {
                    if (ent.Comp.Foo == args.Relation)
                        ent.Comp.Foo = EntityRelation.Null;
                    Dirty(ent);

                }

                private void OnRelationShutdown(Entity<FooComponent> ent, ref ComponentShutdown args)
                {
                    FooComponent.ClearComponentRelations(ent, EntityManager);
                }
            }

                /// <summary>
                /// Auto-generated method that clears all relations in a certain entity.
                /// This has to be called on component shutdown to keep all relations correct.
                /// </summary>
                public static void ClearComponentRelations(Entity<FooComponent> ent, IEntityManager entMan)
                {
                    entMan.ClearRelation(ent.Owner, ref ent.Comp.Foo);

                }
            }

            """);
    }

    [Test]
    public void TestExplicitDirty()
    {
        var result = RunGenerator("""
            [AutoGenerateEntityRelations(true)]
            public sealed partial class FooComponent : IComponent
            {
                [AutoRelationField]
                public EntityRelation Foo;
            }
            """);

        ExpectNoDiagnostics(result);
        ExpectSource(
            result,
            """
            // <auto-generated />

            using Robust.Shared.GameObjects;

            namespace Content.Shared.Access;

            public partial class FooComponent
            {
            [RobustAutoGenerated]
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            public sealed partial class FooComponent_AutoRelationsSystem : EntitySystem
            {
                public override void Initialize()
                {
                    base.Initialize();
                    SubscribeLocalEvent<FooComponent, ComponentShutdown>(OnRelationShutdown);
                    SubscribeLocalEvent<FooComponent, EntityRelationDeleteEvent>(OnRelationDeleted);
                }

                private void OnRelationDeleted(Entity<FooComponent> ent, ref EntityRelationDeleteEvent args)
                {
                    if (ent.Comp.Foo == args.Relation)
                        ent.Comp.Foo = EntityRelation.Null;
                    Dirty(ent);

                }

                private void OnRelationShutdown(Entity<FooComponent> ent, ref ComponentShutdown args)
                {
                    FooComponent.ClearComponentRelations(ent, EntityManager);
                }
            }

                /// <summary>
                /// Auto-generated method that clears all relations in a certain entity.
                /// This has to be called on component shutdown to keep all relations correct.
                /// </summary>
                public static void ClearComponentRelations(Entity<FooComponent> ent, IEntityManager entMan)
                {
                    entMan.ClearRelation(ent.Owner, ref ent.Comp.Foo);

                }
            }

            """);
    }

    [Test]
    public void TestExplicitShutdown()
    {
        var result = RunGenerator("""
            [AutoGenerateEntityRelations(shutdownEvent: false)]
            public sealed partial class FooComponent : IComponent
            {
                [AutoRelationField]
                public EntityRelation Foo;
            }
            """);

        ExpectNoDiagnostics(result);
        ExpectSource(
            result,
            """
            // <auto-generated />

            using Robust.Shared.GameObjects;

            public partial class FooComponent
            {
            [RobustAutoGenerated]
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            public sealed partial class FooComponent_AutoRelationsSystem : EntitySystem
            {
                public override void Initialize()
                {
                    base.Initialize();

                    SubscribeLocalEvent<FooComponent, EntityRelationDeleteEvent>(OnRelationDeleted);
                }

                private void OnRelationDeleted(Entity<FooComponent> ent, ref EntityRelationDeleteEvent args)
                {
                    if (ent.Comp.Foo == args.Relation)
                        ent.Comp.Foo = EntityRelation.Null;

                }


            }

                /// <summary>
                /// Auto-generated method that clears all relations in a certain entity.
                /// This has to be called on component shutdown to keep all relations correct.
                /// </summary>
                public static void ClearComponentRelations(Entity<FooComponent> ent, IEntityManager entMan)
                {
                    entMan.ClearRelation(ent.Owner, ref ent.Comp.Foo);

                }
            }

            """);
    }

    private static void ExpectSource(GeneratorRunResult result, string expected)
    {
        Assert.That(result.GeneratedSources, Has.Length.EqualTo(1));

        var source = result.GeneratedSources[0];

        Assert.That(source.SourceText.ToString(), Is.EqualTo(expected));
    }

    private static void ExpectNoDiagnostics(GeneratorRunResult result)
    {
        Assert.That(result.Diagnostics, Is.Empty);
    }

    private static GeneratorRunResult RunGenerator(string source)
    {
        Compilation compilation = CSharpCompilation.Create("compilation",
            [
                CSharpSyntaxTree.ParseText(source, path: "Source.cs"),
                CSharpSyntaxTree.ParseText(TypesCode, path: "Types.cs")
            ],
            [MetadataReference.CreateFromFile(typeof(Binder).GetTypeInfo().Assembly.Location)],
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new EntityRelationsGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out _, out _);
        var result = driver.GetRunResult();

        return result.Results[0];
    }
}
