using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;
using Robust.Shared.EntitySystemSubscriptionsGenerator;

namespace Robust.Analyzers.Tests;

public sealed class EntitySystemSubscriptionGeneratorTest
{
    private const string TemplateCode = """
            namespace Robust.Shared.GameObjects;

            public sealed partial class System : EntitySystem
            {
                [SubscribeLocalEvent]
                private void TemplateSubscription<T>(Entity<FooComponent> ent, ref T args) where T : IEventConstraint
                {
                }

                [SubscribeLocalEvent]
                private void TemplateNestedSubscription<T>(Entity<FooComponent> ent, ref TemplateEvent<T> args) where T : IEventConstraint
                {
                }

                [SubscribeLocalEvent]
                private void TemplateSuperNestedSubscription<T>(
                    Entity<FooComponent> ent,
                    ref NestedTemplateEvent<NestedTemplateEventNext<T>> args) where T : IEventConstraint
                {
                }

                [SubscribeLocalEvent]
                private void ManyTemplateNestedSubscription<T1, T2>(Entity<FooComponent> ent, ref TemplateEvent<T1, T2> args)
                    where T1 : IEventConstraint
                    where T2 : IEventConstraint
                {
                }

                [SubscribeLocalEvent]
                private void ManyTemplateSuperNestedSubscription<T1, T2>(
                    Entity<FooComponent> ent,
                    ref NestedTemplateEvent<NestedTemplateEventNext<T1, T2>,
                        NestedTemplateEventOther<T1, T2>> args)
                    where T1 : IEventConstraint
                    where T2 : IEventConstraint
                {
                }
            }

            public sealed partial class FooComponent : Component;

            public interface IEventConstraint;

            [GenericEvent]
            public sealed class ClassEvent : IEventConstraint;

            [ByRefEvent, GenericEvent]
            public record struct StructEvent : IEventConstraint;

            [ByRefEvent, GenericEvent]
            public record struct StructEvent1 : IEventConstraint;

            [ByRefEvent, GenericEvent]
            public record struct StructEvent2 : IEventConstraint;

            [ByRefEvent, GenericEvent]
            public record struct StructEvent3 : IEventConstraint;

            [ByRefEvent, GenericEvent]
            public record struct TemplateEvent<T>(T Bar) where T : IEventConstraint;

            public interface INestedFoo;

            [ByRefEvent, GenericEvent]
            public record struct NestedTemplateEvent<T>(T Bar) where T : INestedFoo;

            [ByRefEvent, GenericEvent]
            public record struct NestedTemplateEventNext<T>(T Bar) : INestedFoo where T : IEventConstraint;

            public interface INestedFooMany;

            [ByRefEvent, GenericEvent]
            public record struct TemplateEvent<T1, T2>(T1 Bar, T2 Foo) where T1 : IEventConstraint where T2 : IEventConstraint;

            [ByRefEvent, GenericEvent]
            public record struct NestedTemplateEvent<T1, T2>(T1 Bar, T2 Foo) where T1 : INestedFooMany where T2 : INestedFooMany;

            [ByRefEvent, GenericEvent]
            public record struct NestedTemplateEventNext<T1, T2>(T1 Bar, T2 Foo) : INestedFooMany where T1 : IEventConstraint where T2 : IEventConstraint;

            [ByRefEvent, GenericEvent]
            public record struct NestedTemplateEventOther<T1, T2>(T1 Bar, T2 Foo) : INestedFooMany where T1 : IEventConstraint where T2 : IEventConstraint;
            """;

    private const string TemplateCodeResult = """

        // <auto-generated />

        using Robust.Shared.GameObjects;
        using JetBrains.Annotations;

        #pragma warning disable CS0618 // Type or member is obsolete: event handlers will have their own obsoletion warnings, dont need to dupe them

        namespace Robust.Shared.GameObjects;

        public partial class System
        {
            /// <inheritdoc />
            [MustCallBase]
            public override void AutoSubscriptions()
            {
                base.AutoSubscriptions();

                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.ClassEvent>(TemplateSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.StructEvent>(TemplateSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.StructEvent1>(TemplateSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.StructEvent2>(TemplateSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.StructEvent3>(TemplateSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.ClassEvent>>(TemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent>>(TemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent1>>(TemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent2>>(TemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent3>>(TemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.ClassEvent>>>(TemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent>>>(TemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent1>>>(TemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent2>>>(TemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent3>>>(TemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.ClassEvent>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.StructEvent>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.StructEvent1>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.StructEvent2>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.StructEvent3>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.ClassEvent>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.StructEvent>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.StructEvent1>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.StructEvent2>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.StructEvent3>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.ClassEvent>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.StructEvent>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.StructEvent1>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.StructEvent2>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.StructEvent3>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.ClassEvent>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.StructEvent>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.StructEvent1>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.StructEvent2>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.StructEvent3>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.ClassEvent>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.StructEvent>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.StructEvent1>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.StructEvent2>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.TemplateEvent<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.StructEvent3>>(ManyTemplateNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.ClassEvent>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.ClassEvent>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.StructEvent>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.StructEvent>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.StructEvent1>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.StructEvent1>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.StructEvent2>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.StructEvent2>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.StructEvent3>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.ClassEvent, Robust.Shared.GameObjects.StructEvent3>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.ClassEvent>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.ClassEvent>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.StructEvent>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.StructEvent>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.StructEvent1>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.StructEvent1>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.StructEvent2>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.StructEvent2>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.StructEvent3>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent, Robust.Shared.GameObjects.StructEvent3>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.ClassEvent>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.ClassEvent>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.StructEvent>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.StructEvent>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.StructEvent1>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.StructEvent1>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.StructEvent2>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.StructEvent2>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.StructEvent3>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent1, Robust.Shared.GameObjects.StructEvent3>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.ClassEvent>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.ClassEvent>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.StructEvent>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.StructEvent>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.StructEvent1>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.StructEvent1>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.StructEvent2>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.StructEvent2>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.StructEvent3>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent2, Robust.Shared.GameObjects.StructEvent3>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.ClassEvent>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.ClassEvent>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.StructEvent>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.StructEvent>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.StructEvent1>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.StructEvent1>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.StructEvent2>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.StructEvent2>>>(ManyTemplateSuperNestedSubscription);
                SubscribeLocalEvent<Robust.Shared.GameObjects.FooComponent, Robust.Shared.GameObjects.NestedTemplateEvent<Robust.Shared.GameObjects.NestedTemplateEventNext<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.StructEvent3>, Robust.Shared.GameObjects.NestedTemplateEventOther<Robust.Shared.GameObjects.StructEvent3, Robust.Shared.GameObjects.StructEvent3>>>(ManyTemplateSuperNestedSubscription);

            }
        }


        """;

    [Test]
    public void TestTemplate()
    {
        var result = RunGenerator(TemplateCode);
        ExpectNoDiagnostics(result);
        ExpectSource(result, TemplateCodeResult);
    }

    private static void ExpectNoDiagnostics(GeneratorRunResult result)
    {
        Assert.That(result.Diagnostics, Is.Empty);
    }

    private static void ExpectSource(GeneratorRunResult result, string expected)
    {
        Assert.That(result.GeneratedSources, Has.Length.EqualTo(1));

        var source = result.GeneratedSources[0];

        Assert.That(source.SourceText.ToString(), Is.EqualTo(expected));
    }

    private static GeneratorRunResult RunGenerator(string source)
    {
        var compilation = (Compilation)CSharpCompilation.Create("compilation",
            [
                CSharpSyntaxTree.ParseText(source, path: "Source.cs")
            ],
            new[] { MetadataReference.CreateFromFile(typeof(Binder).GetTypeInfo().Assembly.Location) },
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new EntitySystemSubscriptionGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var newCompilation, out _);
        var result = driver.GetRunResult();

        return result.Results[0];
    }
}
