using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Robust.Client.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class DevWindowUIPopup : Popup
{
    public string? Text
    {
        get => TextLabel.Text;
        set => TextLabel.Text = value;
    }

    public DevWindowUIPopup()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }
}
