using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.UserInterface;

[GenerateTypedNameReferences]
internal sealed partial class ProfTreeLine : Control
{
    public ProfTreeLine()
    {
        RobustXamlLoader.Load(this);
    }
}
