# Used internally by the THE() function.
zzzz-the = { PROPER($ent) ->
    *[false] the { $ent }
     [true] { $ent }
    }

pronouns-subject = Subject
pronouns-subject-desc = eg. "I think HE is very nice".
# Used internally by the SUBJECT() function (autogenerated).
zzzz-subject-pronoun = { $gender ->
    [male] he
    [female] she
    [epicene] they
    [neuter] it
   *[other] { $gender }
   }

pronouns-object = Object
pronouns-object-desc = eg. "I met HER recently".
# Used internally by the OBJECT() function (autogenerated).
zzzz-object-pronoun = { $gender ->
    [male] him
    [female] her
    [epicene] them
    [neuter] it
   *[other] { $gender }
   }

pronouns-dative = Dative
pronouns-dative-desc = Not used in English.
# Used internally by the DAT-OBJ() function (autogenerated).
# Not used in en-US. Created to support other languages.
# (e.g., "to him," "for her")
zzzz-dat-object = { $gender ->
    [male] him
    [female] her
    [epicene] them
    [neuter] it
   *[other] { $gender }
   }

pronouns-genitive = Genitive
pronouns-genitive-desc = Not used in English.
# Used internally by the GENITIVE() function (autogenerated).
# Not used in en-US. Created to support other languages.
# e.g., "у него" (Russian), "seines Vaters" (German).
zzzz-genitive = { $gender ->
    [male] his
    [female] her
    [epicene] their
    [neuter] its
   *[other] { $gender }
   }

pronouns-plurality = Should this conjugate plurally?
pronouns-plurality-desc = eg. singular "she is", plural "they are".

pronouns-possessive-pronoun = Possessive Pronoun
pronouns-possessive-pronoun-desc = eg. "Is this THEIR dog?"
# Used internally by the POSS-PRONOUN() function (autogenerated).
zzzz-possessive-pronoun = { $gender ->
    [male] his
    [female] hers
    [epicene] theirs
    [neuter] its
   *[other] { $gender }
   }

pronouns-possessive-adj = Possessive Adjective
pronouns-possessive-adj-desc = "They told me that the house is THEIRS".
# Used internally by the POSS-ADJ() function (autogenerated).
zzzz-possessive-adjective = { $gender ->
    [male] his
    [female] her
    [epicene] their
    [neuter] its
   *[other] { $gender }
   }

pronouns-reflexive = Reflexive
pronouns-reflexive-desc = "It said it would rather do that ITSELF".
# Used internally by the REFLEXIVE() function (autogenerated).
zzzz-reflexive-pronoun = { $gender ->
    [male] himself
    [female] herself
    [epicene] themselves
    [neuter] itself
   *[other] { $gender }
   }

pronouns-counter = Counter
pronouns-counter-desc = Not used in English.

pronouns-conjugate-be = Conjugate 'to be'
pronouns-conjugate-be-desc = 'epicene' for ARE, otherwise IS
# Used internally by the CONJUGATE-BE() function (autogenerated).
zzzz-conjugate-be = { $gender ->
    [epicene] are
   *[other] is
   }

pronouns-conjugate-have = Conjugate 'to have'
pronouns-conjugate-have-desc = 'epicene' for HAVE, otherwise HAS
# Used internally by the CONJUGATE-HAVE() function (autogenerated).
zzzz-conjugate-have = { $gender ->
    [epicene] have
   *[other] has
   }

pronouns-conjugate-basic = Basic Conjugation
pronouns-conjugate-basic-desc = 'epicene' for no affix, otherwise -S (eg. they run / it runs)
# Used internally by the CONJUGATE-BASIC() function.
zzzz-conjugate-basic = { $gender ->
    [epicene] { $first }
   *[other] { $second }
   }

pronouns-noun-prefix = Noun Prefix
pronouns-noun-prefix-desc = Not used in English.

pronouns-noun-suffix = Noun Suffix
pronouns-noun-suffix-desc = Not used in English.

pronouns-noun-affixes = Noun Affixes
pronouns-noun-affixes-desc = Not used in English.
