# Used internally by the THE() function.
zzzz-the = { PROPER($ent) ->
    *[false] the { $ent }
     [true] { $ent }
    }

# Used internally by the SUBJECT() function (autogenerated).
zzzz-subject-pronoun = { $gender ->
    [male] he
    [female] she
    [epicene] they
    [neuter] it
   *[other] { $gender }
   }

# Used internally by the OBJECT() function (autogenerated).
zzzz-object-pronoun = { $gender ->
    [male] him
    [female] her
    [epicene] them
    [neuter] it
   *[other] { $gender }
   }

# Used internally by the DAT-OBJ() function (autogenerated).
# Not used in en-US. Created to support other languages.
# (e.g., "to him," "for her")
zzzz-dat-object = { $gender ->
    [male] him
    [female] her
    [epicene] them
    [neuter] it
   *[other] { $gender }
   }

# Used internally by the GENITIVE() function (autogenerated).
# Not used in en-US. Created to support other languages.
# e.g., "у него" (Russian), "seines Vaters" (German).
zzzz-genitive = { $gender ->
    [male] his
    [female] her
    [epicene] their
    [neuter] its
   *[other] { $gender }
   }

# Used internally by the POSS-PRONOUN() function (autogenerated).
zzzz-possessive-pronoun = { $gender ->
    [male] his
    [female] hers
    [epicene] theirs
    [neuter] its
   *[other] { $gender }
   }

# Used internally by the POSS-ADJ() function (autogenerated).
zzzz-possessive-adjective = { $gender ->
    [male] his
    [female] her
    [epicene] their
    [neuter] its
   *[other] { $gender }
   }

# Used internally by the REFLEXIVE() function (autogenerated).
zzzz-reflexive-pronoun = { $gender ->
    [male] himself
    [female] herself
    [epicene] themselves
    [neuter] itself
   *[other] { $gender }
   }

# Used internally by the CONJUGATE-BE() function (autogenerated).
zzzz-conjugate-be = { $gender ->
    [epicene] are
   *[other] is
   }

# Used internally by the CONJUGATE-HAVE() function (autogenerated).
zzzz-conjugate-have = { $gender ->
    [epicene] have
   *[other] has
   }

# Used internally by the CONJUGATE-BASIC() function.
zzzz-conjugate-basic = { $gender ->
    [epicene] { $first }
   *[other] { $second }
   }
