using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Robust.Roslyn.Shared;

namespace Robust.Analyzers.Generators;

[Generator]
public sealed class EntitySystemGenerator : IIncrementalGenerator
{
    private const string EntitySystem = "Robust.Shared.GameObjects.EntitySystem";
    private const string Update = "Update";
    private const string FrameUpdate = "FrameUpdate";

    public void Initialize(IncrementalGeneratorInitializationContext initContext)
    {
        var systems = initContext
            .SyntaxProvider
            .CreateSyntaxProvider<(TypeDeclarationSyntax type, INamedTypeSymbol symbol)?>(
                static (node, _) => node is ClassDeclarationSyntax,
                static (context, cancel) =>
                {
                    var type = (TypeDeclarationSyntax)context.Node;
                    if (context.SemanticModel.GetDeclaredSymbol(type, cancel) is not INamedTypeSymbol symbol)
                        return null;

                    if (TypeSymbolHelper.ShittyTypeMatch(symbol, EntitySystem))
                        return null;

                    if (!TypeSymbolHelper.Inherits(symbol, EntitySystem))
                        return null;

                    return (type, symbol);
                }
            )
            .Where(static type => type != null);

        initContext.RegisterSourceOutput(
            systems.Collect(),
            static (context, tuples) =>
            {
                // Did you know netstandard has no DistinctBy, and that the documentation is extremely lacking
                // as to how you deduplicate multiple partial types found for the same class
                // Microsoft's solution was to throw an error and require you to attribute your type
                // We ain't doing all that

                var set = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
                foreach (var tuple in tuples)
                {
                    var type = tuple!.Value.type;
                    var symbol = tuple!.Value.symbol;

                    var info = PartialTypeInfo.FromSymbol(symbol, type);
                    if (!info.IsValid)
                        continue;

                    if (!set.Add(symbol))
                        continue;

                    var needsUpdate = "false";
                    var needsFrameUpdate = "false";
                    foreach (var member in symbol.GetMembers())
                    {
                        if (member is not IMethodSymbol method)
                            continue;

                        if (method.IsOverride &&
                            method.Name is Update or FrameUpdate &&
                            !TypeSymbolHelper.ShittyTypeMatch(method.ContainingType, EntitySystem) &&
                            method.OverriddenMethod?.ContainingType is { } containing &&
                            TypeSymbolHelper.ShittyTypeMatch(containing, EntitySystem))
                        {
                            switch (method.Name)
                            {
                                case Update:
                                    needsUpdate = "true";
                                    break;
                                case FrameUpdate:
                                    needsFrameUpdate = "true";
                                    break;
                            }
                        }
                    }

                    var sb = new IndentWriter(new StringBuilder());
                    sb.AppendLine("// <auto-generated />");
                    sb.AppendLine();

                    info.WriteHeader(ref sb);

                    sb.Append(": global::Robust.Shared.GameObjects.IEntitySystem");
                    sb.AppendLine();
                    sb.AppendOpeningBrace();

                    sb.AppendLine($$"""
                            bool? global::Robust.Shared.GameObjects.IEntitySystem.NeedsUpdate()
                            {
                                return {{needsUpdate}};
                            }

                            bool? global::Robust.Shared.GameObjects.IEntitySystem.NeedsFrameUpdate()
                            {
                                return {{needsFrameUpdate}};
                            }
                        """);

                    sb.AppendClosingBrace();
                    info.WriteFooter(ref sb);

                    var file = info.GetGeneratedFileName("NeedsUpdate");
                    context.AddSource(file, sb.ToString());
                }
            }
        );
    }
}
