using System;
using System.Collections.Generic;
using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.Editor.Interface;

/// <summary>
/// Tabbed panel managed by <see cref="EditorDocker"/>.
/// Contains the actual tabs themselves and also the content body.
/// </summary>
[Virtual]
[GenerateTypedNameReferences]
public partial class EditorTabPanel : Control
{
    public const float MarginSize = 80;

    /// <summary>
    /// Docker that owns this panel.
    /// </summary>
    public EditorDocker Owner { get; }

    private readonly EditorTabBar _tabs;
    private readonly List<PanelData> _panels = new();
    private readonly ButtonGroup _buttonGroup = new();

    public bool AllowSplitting { get; set; }

    public int PanelCount => _panels.Count;

    internal IEnumerable<EditorPanel> Panels => _panels.Select(x => x.Panel);

    public EditorTabPanel(EditorDocker owner)
    {
        Owner = owner;
        RobustXamlLoader.Load(this);

        TabsContainer.AddChild(_tabs = new EditorTabBar(this));

        DropOverlay.MarginSize = MarginSize;
        DropOverlay.OnDragDrop += DropOverlayDragDropped;
    }

    public void AddPanel(EditorPanel panel)
    {
        var tab = new EditorTab(panel, _tabs);
        tab.Button.OnPressed += _ => SelectTab(tab);
        tab.Button.Group = _buttonGroup;
        _tabs.Tabs.AddChild(tab);

        _panels.Add(new PanelData(panel, tab));

        Owner.ChildPanelAdded(panel);

        Owner.CheckPendingRemoval();

        SelectTab(tab);
    }

    public void RemovePanel(EditorPanel panel, bool destroy = true)
    {
        Content.Children.Remove(panel);

        var panelData = _panels.Single(x => x.Panel == panel);
        _panels.Remove(panelData);
        panelData.Tab.Button.Group = null;

        _tabs.Tabs.RemoveChild(panelData.Tab);

        Owner.ChildPanelRemoved(panel);

        if (destroy)
            ConfirmRemoval();
        else
            Owner.CheckPendingRemoval();

        if (Content.ChildCount == 0 && _panels.Count > 0)
            SelectTab(_panels[0].Tab);
    }

    public void ConfirmRemoval()
    {
        if (_panels.Count == 0)
            Owner.RemoveTabPanel(this);
    }

    private void SelectTab(EditorTab tab)
    {
        if (tab.Panel.Parent != Content)
        {
            Content.RemoveAllChildren();
            Content.AddChild(_panels.Single(x => x.Tab == tab).Panel);
        }

        tab.Panel.TabFocused();
        tab.Button.Pressed = true;
    }

    public override void DragEnter(DragEnterEventArgs eventArgs)
    {
        if (eventArgs.Operation is EditorTabDragDrop && AllowSplitting)
        {
            DropOverlay.Visible = true;
        }
    }

    public override void DragLeave(DragLeaveEventArgs eventArgs)
    {
        if (eventArgs.Operation is EditorTabDragDrop)
        {
            DropOverlay.Visible = false;
        }
    }

    private void DropOverlayDragDropped(DragDropEventArgs eventArgs)
    {
        if (eventArgs.Operation is not EditorTabDragDrop dragDrop || !AllowSplitting)
            return;

        var pos = eventArgs.RelativePosition;
        var size = DropOverlay.Size;

        var minDist = float.PositiveInfinity;
        DockRelative? minRelative = null;

        TestEdge(pos.X, DockRelative.Left);
        TestEdge(pos.Y, DockRelative.Up);
        TestEdge(size.X - pos.X, DockRelative.Right);
        TestEdge(size.Y - pos.Y, DockRelative.Down);

        void TestEdge(float dist, DockRelative relative)
        {
            dist = Math.Abs(dist);
            if (dist < minDist && dist < MarginSize)
            {
                minDist = dist;
                minRelative = relative;
            }
        }

        if (minRelative != null)
        {
            eventArgs.Handle();

            Owner.AddPanelRelative(dragDrop.Panel, this, minRelative.Value);
        }

        DropOverlay.Visible = false;
    }

    private sealed class PanelData
    {
        public readonly EditorPanel Panel;
        public readonly EditorTab Tab;

        public PanelData(EditorPanel panel, EditorTab tab)
        {
            Panel = panel;
            Tab = tab;
        }
    }
}
