using System.Collections.Immutable;
using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Log;
using Robust.Shared.Utility;

namespace Robust.Client.Editor.Interface;

[Virtual]
[GenerateTypedNameReferences]
public partial class EditorTabBar : Control
{
    private ImmutableArray<string> _additionalStyleClasses = [];

    public EditorTabPanel Owner { get; }
    public ImmutableArray<string> AdditionalStyleClasses
    {
        get => _additionalStyleClasses;
        set
        {
            StyleClasses.RemoveRange(_additionalStyleClasses);

            _additionalStyleClasses = value;

            StyleClasses.AddRange(_additionalStyleClasses);
        }
    }

    public EditorTabBar(EditorTabPanel owner)
    {
        Owner = owner;
        RobustXamlLoader.Load(this);
    }

    public override void DragLeave(DragLeaveEventArgs eventArgs)
    {
        if (eventArgs.Operation is EditorTabDragDrop tabDrop)
        {
            if (EditorPanelScope.DockCheck(Owner.Owner.Scope, tabDrop.Panel.Scope))
            {
                Logger.DebugS("ui.editor", "LEAVING");
                Owner.RemovePanel(tabDrop.Panel, destroy: false);
            }
        }
    }

    public override void DragEnter(DragEnterEventArgs eventArgs)
    {
        if (eventArgs.Operation is EditorTabDragDrop tabDrop)
        {
            if (EditorPanelScope.DockCheck(Owner.Owner.Scope, tabDrop.Panel.Scope))
            {
                Logger.DebugS("ui.editor", "ENTERING");
                if (Tabs.Children.Select(x => (x as EditorTab)?.Panel).Contains(tabDrop.Panel))
                    return;

                Owner.AddPanel(tabDrop.Panel);
            }
        }
    }

    public override void DragDrop(DragDropEventArgs eventArgs)
    {
        if (eventArgs.Operation is EditorTabDragDrop tabDrop)
        {
            if (EditorPanelScope.DockCheck(Owner.Owner.Scope, tabDrop.Panel.Scope))
                eventArgs.Handle();
        }
    }
}
