using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Robust.Client.Editor.Interface;

[Virtual]
[GenerateTypedNameReferences]
public partial class EditorTab : Control
{
    public const string StyleClassEditorTabButton = "EditorTabButton";
    public const string StyleClassEditorTabButtonSmall = "EditorTabButtonSmall";

    public EditorPanel Panel { get; }

    public EditorTabBar TabBar { get; }

    public string? TitleText
    {
        get => Title.Text;
        set => Title.Text = value;
    }

    [Access(typeof(EditorTabPanel))]
    internal EditorTab(EditorPanel panel, EditorTabBar tabBar)
    {
        Panel = panel;
        TabBar = tabBar;
        RobustXamlLoader.Load(this);

        Button.OnKeyBindDown += ButtonDragStart;
        CloseButton.OnPressed += CloseButtonOnOnPressed;
    }

    private void ButtonDragStart(GUIBoundKeyEventArgs obj)
    {
        if (obj.Function != EngineKeyFunctions.UIClick)
            return;

        obj.HandleDragDetect(DragDetected);
    }

    private DragDropDetectResult DragDetected(GUIBoundKeyEventArgs _)
    {
        EditorTabBaseDragDrop operation = Panel.CanUndock
            ? new EditorTabDragDrop(Panel, TabBar.Owner)
            : new EditorTabOnlyReorderDragDrop(Panel, TabBar.Owner);
        return DragDropDetectResult.Start(this, operation);
    }

    private void UpdateInfo()
    {
        CloseButton.Visible = Panel.CanClose;
        TitleText = Panel.Title;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        Panel.TabInfoChanged += PanelOnTabInfoChanged;
        UpdateInfo();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        Panel.TabInfoChanged -= PanelOnTabInfoChanged;
    }

    private void PanelOnTabInfoChanged()
    {
        UpdateInfo();
    }

    private void CloseButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        TabBar.Owner.RemovePanel(Panel);
        Panel.TabClosed();
    }
}
