using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Robust.Client.Editor.Interface;

[Virtual]
[GenerateTypedNameReferences]
public partial class EditorTab : Control
{
    public EditorPanel Panel { get; }

    public EditorTabBar TabBar { get; }

    public string? TitleText
    {
        get => Title.Text;
        set => Title.Text = value;
    }

    public EditorTab(EditorPanel panel, EditorTabBar tabBar)
    {
        Panel = panel;
        TabBar = tabBar;
        RobustXamlLoader.Load(this);

        Button.OnKeyBindDown += ButtonDragStart;
    }

    private void ButtonDragStart(GUIBoundKeyEventArgs obj)
    {
        if (obj.Function != EngineKeyFunctions.UIClick)
            return;

        obj.HandleDragDetect(DragDetected);
    }

    private DragDropDetectResult DragDetected(GUIBoundKeyEventArgs _)
    {
        return DragDropDetectResult.Start(this, new EditorTabDragDrop(Panel));
    }
}
