using System;
using System.Collections.Generic;
using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.Editor.Styling;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Stylesheets;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Robust.Client.Editor.Interface;

/// <summary>
/// A UI control used for editor-like tabbable and dockable panels.
/// </summary>
/// <remarks>
/// <para>
/// This control owns multiple <see cref="EditorPanel"/>s,
/// which it can move between different <see cref="EditorTabPanel"/>s it creates dynamically.
/// These get created even on different windows (via popout) in some cases.
/// </para>
/// <para>
/// This control is intended to interact with OS windows for its functions.
/// It is not currently intended to work inside a single window or on fullscreen.
/// </para>
/// </remarks>
[Virtual]
[GenerateTypedNameReferences]
public partial class EditorDocker : Control
{
    private readonly List<EditorTabPanel> _tabPanels = new();
    private bool _allowSplitting = true;

    public bool AllowSplitting
    {
        get => _allowSplitting;
        set
        {
            _allowSplitting = value;
            foreach (var panel in _tabPanels)
            {
                panel.AllowSplitting = value;
            }
        }
    }

    public event Action<EditorPanel>? PanelAdded;
    public event Action<EditorPanel>? PanelRemoved;

    public EditorDocker()
    {
        RobustXamlLoader.Load(this);
    }

    public void AddPanel(EditorPanel panel)
    {
        if (_tabPanels.Count == 0)
        {
            Content.AddChild(NewTabPanel(panel));
        }
        else
        {
            AddPanelRelative(panel, _tabPanels[0], DockRelative.Tab);
        }
    }

    public void AddPanelRelative(EditorPanel newPanel, EditorTabPanel relativeTo, DockRelative relative)
    {
        if (relative == DockRelative.Tab)
        {
            relativeTo.AddPanel(newPanel);
            return;
        }

        var parent = relativeTo.Parent;
        var pos = relativeTo.GetPositionInParent();
        relativeTo.Orphan();

        var splitter = new EditorDockerSplitter();
        splitter.Orientation = relative switch
        {
            DockRelative.Up or DockRelative.Down => SplitContainer.SplitOrientation.Vertical,
            DockRelative.Left or DockRelative.Right => SplitContainer.SplitOrientation.Horizontal,
            _ => throw new ArgumentOutOfRangeException(nameof(relative), relative, null)
        };

        parent!.AddChild(splitter);
        splitter.SetPositionInParent(pos);

        var newTabPanel = NewTabPanel(newPanel);

        switch (relative)
        {
            case DockRelative.Up:
            case DockRelative.Left:
                splitter.AddChild(newTabPanel);
                splitter.AddChild(relativeTo);
                break;
            case DockRelative.Down:
            case DockRelative.Right:
                splitter.AddChild(relativeTo);
                splitter.AddChild(newTabPanel);
                break;
        }
    }

    private EditorTabPanel NewTabPanel(EditorPanel tab)
    {
        var tabPanel = new EditorTabPanel(this);
        tabPanel.AllowSplitting = _allowSplitting;
        _tabPanels.Add(tabPanel);
        tabPanel.AddPanel(tab);
        return tabPanel;
    }

    public void RemoveTabPanel(EditorTabPanel editorTabPanel)
    {
        var removed = _tabPanels.Remove(editorTabPanel);
        DebugTools.Assert(removed, "Tab was not owned by this EditorDocker!");

        var parent = editorTabPanel.Parent;

        editorTabPanel.Orphan();

        if (parent == Content)
        {
            // Last editor in this docker.
            LastTabRemoved();
        }
        else if (parent is EditorDockerSplitter splitter)
        {
            var sibling = splitter.Children.Single(x => x is EditorTabPanel or EditorDockerSplitter);
            sibling.Orphan();

            var grandParent = parent.Parent;
            DebugTools.AssertNotNull(grandParent);

            splitter.Orphan();

            grandParent!.AddChild(sibling);
        }
        else
        {
            throw new InvalidOperationException("EditorTabPanel has invalid parent when removed from EditorDocker!");
        }
    }

    internal void CheckPendingRemoval()
    {
        if (_tabPanels.All(static x => x.PanelCount == 0))
            LastTabPendingRemoval();
        else
            LastTabNotPendingRemoval();
    }

    protected virtual void LastTabPendingRemoval()
    {

    }

    protected virtual void LastTabNotPendingRemoval()
    {

    }

    protected virtual void LastTabRemoved()
    {

    }

    [Access(typeof(EditorTabPanel))]
    internal void ChildPanelAdded(EditorPanel panel)
    {
        PanelAdded?.Invoke(panel);
    }

    [Access(typeof(EditorTabPanel))]
    internal void ChildPanelRemoved(EditorPanel panel)
    {
        PanelRemoved?.Invoke(panel);
    }

    public IEnumerable<EditorPanel> GetAllPanels()
    {
        foreach (var tabPanel in _tabPanels)
        {
            foreach (var panel in tabPanel.Panels)
            {
                yield return panel;
            }
        }
    }
}

/// <summary>
/// Directions in which you can dock a <see cref="EditorPanel"/> relative to an existing <see cref="EditorTabPanel"/>.
/// </summary>
public enum DockRelative : byte
{
    /// <summary>
    /// The panel is docked as a sibling tab on the same <see cref="EditorTabPanel"/>.
    /// </summary>
    Tab,

    /// <summary>
    /// The panel is docked in a new <see cref="EditorTabPanel"/> above the specified panel.
    /// </summary>
    Up,

    /// <summary>
    /// The panel is docked in a new <see cref="EditorTabPanel"/> below the specified panel.
    /// </summary>
    Down,

    /// <summary>
    /// The panel is docked in a new <see cref="EditorTabPanel"/> left of the specified panel.
    /// </summary>
    Left,

    /// <summary>
    /// The panel is docked in a new <see cref="EditorTabPanel"/> right of the specified panel.
    /// </summary>
    Right
}

/// <summary>
/// <see cref="EditorDocker"/> which owns its parent window and will close it if all panels in it get closed.
/// </summary>
internal sealed class EditorWindowDocker : EditorDocker
{
    [Dependency] private readonly IEngineStylesheetManager _stylesheets = null!;

    private readonly OSWindow _window;

    public EditorWindowDocker(OSWindow window)
    {
        IoCManager.InjectDependencies(this);

        _window = window;
        AllowSplitting = false;

        window.Closed += WindowOnClosed;
    }

    public static (OSWindow, EditorWindowDocker) Create()
    {
        var clyde = IoCManager.Resolve<IClyde>();
        var window = new OSWindow { Owner = clyde.MainWindow };
        var docker = new EditorWindowDocker(window);
        window.AddChild(docker);

        return (window, docker);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _stylesheets.UseStylesheet(this, sa => sa.GetEditorDark());
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _stylesheets.StopStylesheet(this);
    }

    private void WindowOnClosed()
    {
        foreach (var panel in GetAllPanels())
        {
            panel.TabClosed();
        }
    }

    protected override void LastTabPendingRemoval()
    {
        if (_window.ClydeWindow != null)
            _window.ClydeWindow.Opacity = 0.5f;
    }

    protected override void LastTabNotPendingRemoval()
    {
        if (_window.ClydeWindow != null)
            _window.ClydeWindow.Opacity = 1f;
    }

    protected override void LastTabRemoved()
    {
        _window.Close();
    }
}

