using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.Editor.Interface;

/// <summary>
/// Represents an editor panel that can be docked around by dragging the tab header.
/// </summary>
[Virtual]
[GenerateTypedNameReferences]
public partial class EditorPanel : Control
{
    public EditorPanel()
    {
        RobustXamlLoader.Load(this);
    }

    public virtual string Title => "";

}
