using System;

namespace Robust.Shared.Serialization.Manager.Attributes
{
    public class DataClassAttribute : Attribute
    {
        /// <summary>
        /// Autogenerated Class if null.
        /// </summary>
        public readonly Type? DataClassType;

        public DataClassAttribute(){}

        public DataClassAttribute(Type dataClassType)
        {
            DataClassType = dataClassType;
        }
    }
}
