#!/usr/bin/env python3
"""Injects build git information into server_config.toml during CI.

This script appends a [build] section with repository and RT submodule info
to the server config file. It runs after the build but before packaging,
so the values get baked into the server ZIP.

Usage:
    python Tools/inject_build_info.py

Environment variables (set by GitHub Actions):
    GITHUB_SERVER_URL   - e.g. "https://github.com"
    GITHUB_REPOSITORY   - e.g. "MyFork/space-station-14"
    GITHUB_SHA          - Full commit SHA
    GITHUB_REF_NAME     - Branch or tag name
"""

import os
import re
import subprocess
import sys


def get_git_info(cwd, default_branch=""):
    """Get git remote URL, commit SHA, and branch for a given directory."""
    try:
        url = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            capture_output=True, text=True, cwd=cwd
        ).stdout.strip()
        sha = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True, text=True, cwd=cwd
        ).stdout.strip()
        branch = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True, text=True, cwd=cwd
        ).stdout.strip()
        if branch == "HEAD":
            branch = default_branch
        return url, sha, branch
    except Exception as e:
        print(f"Warning: could not get git info for {cwd}: {e}", file=sys.stderr)
        return "", "", ""


def main():
    server_url = os.environ.get("GITHUB_SERVER_URL", "https://github.com")
    repo = os.environ.get("GITHUB_REPOSITORY", "")

    # main repo info
    root_url, root_sha, root_branch = get_git_info(".")
    if repo:
        fork_url = f"{server_url}/{repo}"
    else:
        fork_url = root_url
    commit = os.environ.get("GITHUB_SHA", "") or root_sha
    branch = os.environ.get("GITHUB_REF_NAME", "") or root_branch

    # RobustToolbox submodule info
    rt_url, rt_sha, rt_branch = get_git_info("RobustToolbox", default_branch=branch)

    # --- Determine the config file to modify ---
    # The Content.Server/server_config.toml is the template that gets
    # copied to the build output by the csproj's PreserveNewest.
    # Modifying it in CI is safe because it runs in a disposable workspace.

    config_path = os.environ.get("SERVER_CONFIG_PATH", "Content.Server/server_config.toml")

    if not os.path.exists(config_path):
        print(f"Config file not found at {config_path}", file=sys.stderr)
        sys.exit(1)

    # Build the TOML section
    build_section = f"""

[build]
# Auto-generated by CI pipeline. Do not edit manually.
fork_url = "{fork_url}"
hash = "{commit}"
branch = "{branch}"
robust_toolbox_url = "{rt_url}"
robust_toolbox_hash = "{rt_sha}"
robust_toolbox_branch = "{rt_branch}"
"""

    # Read existing content
    with open(config_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Remove any existing [build] section (replace it)
    content = re.sub(
        r'\n\[build\].*?(?=\n\[|\Z)',
        '',
        content,
        flags=re.DOTALL
    )

    # Append the new [build] section and write back
    content += build_section
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Successfully injected build info into {config_path}")
    print(f"   build.fork_url              = {fork_url}")
    print(f"   build.hash                  = {commit}")
    print(f"   build.branch                = {branch}")
    print(f"   build.robust_toolbox_url    = {rt_url}")
    print(f"   build.robust_toolbox_hash   = {rt_sha}")
    print(f"   build.robust_toolbox_branch = {rt_branch}")


if __name__ == "__main__":
    main()

