using System;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.UserInterface.Controls;

[GenerateTypedNameReferences]
[Access(typeof(ColorSelectorSliders))]
public sealed partial class AlphaSliderChannel : BoxContainer, ISliderChannel
{
    public event Action<Range>? OnSliderValueChanged;
    public event Action<ValueChangedEventArgs>? OnSpinValueChanged;

    public Func<int, bool>? IsInputValid
    {
        set => InputBox.IsValid = value;
    }

    public float Value
    {
        get => AlphaSlider.Value;
        set => AlphaSlider.Value = value;
    }

    public AlphaSliderChannel()
    {
        RobustXamlLoader.Load(this);
        AlphaSlider.OnValueChanged += v => OnSliderValueChanged?.Invoke(v);
        InputBox.ValueChanged += args => OnSpinValueChanged?.Invoke(args);
        InputBox.InitDefaultButtons();
    }

    public void OverrideValue(float value, float divisor)
    {
        AlphaSlider.SetValueWithoutEvent(value);
        InputBox.OverrideValue((int)(value * divisor));
    }
}
