using System;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.UserInterface.Controls;

[GenerateTypedNameReferences]
[Access(typeof(ColorSelectorSliders))]
public sealed partial class ColorSliderChannel : BoxContainer, ISliderChannel
{
    public event Action<Range>? OnSliderValueChanged;
    public event Action<ValueChangedEventArgs>? OnSpinValueChanged;

    public Func<int, bool>? IsInputValid
    {
        set => InputBox.IsValid = value;
    }

    public float Value
    {
        get => ColorSlider.Value;
        set => ColorSlider.Value = value;
    }

    public StyleBox? SliderStyleBoxOverride
    {
        set => ColorSlider.BackgroundStyleBoxOverride = value;
    }

    public string LabelText
    {
        set => ChannelLabel.Text = value;
    }

    public ColorSliderChannel()
    {
        RobustXamlLoader.Load(this);
        ColorSlider.OnValueChanged += v => OnSliderValueChanged?.Invoke(v);
        InputBox.ValueChanged += args => OnSpinValueChanged?.Invoke(args);
        InputBox.InitDefaultButtons();
    }

    public void OverrideValue(float value, float divisor)
    {
        ColorSlider.SetValueWithoutEvent(value);
        InputBox.OverrideValue((int)(value * divisor));
    }
}
