using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.UserInterface.Controls;

[GenerateTypedNameReferences, Virtual]
public partial class FilteredItemList : BoxContainer
{
    public FilteredItemList()
    {
        RobustXamlLoader.Load(this);
        FilterLineEdit.OnTextChanged += UpdateFilter;
    }

    public void ReapplyFilter() => UpdateFilter();

    private void UpdateFilter(LineEdit.LineEditEventArgs _ = null!)
    {
        foreach (var item in ItemList)
        {
            if(item.Text == null) continue;

            item.Visible = string.IsNullOrEmpty(FilterLineEdit.Text) ||
                           item.Text.ToLowerInvariant().Contains(FilterLineEdit.Text.Trim().ToLowerInvariant());
        }
    }
}
