using Robust.Client.AutoGenerated;
using Robust.Client.Editor.Styling;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Stylesheets;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Robust.Client.Editor.Testing;

[GenerateTypedNameReferences]
internal sealed partial class EditorDebugControl : Control
{
    [Dependency] private readonly IEngineStylesheetManager _stylesheets = null!;

    public EditorDebugControl()
    {
        IoCManager.InjectDependencies(this);

        RobustXamlLoader.Load(this);

        Docker.AddPanel(new EditorDebugPanel("A"));
        Docker.AddPanel(new EditorDebugPanel("B"));
        Docker.AddPanel(new EditorDebugPanel("C"));
        Docker.AddPanel(new EditorDebugPanel("D"));
        Docker.AddPanel(new EditorDebugPanel("E"));
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _stylesheets.UseStylesheet(this, sa => sa.GetEditorDark());
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _stylesheets.StopStylesheet(this);
    }

}
