using Robust.Client.AutoGenerated;
using Robust.Client.Editor.Interface;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.Editor.Testing;

[Virtual]
[GenerateTypedNameReferences]
public partial class EditorDebugPanel : EditorPanel
{
    private readonly string _foo;

    public EditorDebugPanel(string foo)
    {
        _foo = foo;
        RobustXamlLoader.Load(this);

        A.Text = foo;
    }

    public override string Title => _foo;
}
