using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.Editor.Testing;

[GenerateTypedNameReferences]
internal sealed partial class EditorDebugControl : Control
{
    public EditorDebugControl()
    {
        RobustXamlLoader.Load(this);

        Docker.AddPanel(new EditorDebugPanel("A"));
        Docker.AddPanel(new EditorDebugPanel("B"));
        Docker.AddPanel(new EditorDebugPanel("C"));
        Docker.AddPanel(new EditorDebugPanel("D"));
        Docker.AddPanel(new EditorDebugPanel("E"));
    }
}
