using Robust.Client.AutoGenerated;
using Robust.Client.Editor.Interface;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.Editor.Testing;

[Virtual]
[GenerateTypedNameReferences]
public partial class EditorDebugPanel : EditorPanel
{
    public EditorDebugPanel(string foo)
    {
        RobustXamlLoader.Load(this);

        Title = foo;
    }
}
