name: Build All Configurations

on:
  push:
    branches: [master]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'merge_group' }}

jobs:
  build:
    strategy:
      matrix:
        targetOS: [Windows, Linux, MacOS]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 10.0.x

      - name: Install dependencies
        run: dotnet restore /p:TargetOS=${{ matrix.targetOS }}
      - name: Build Debug
        run: dotnet build --no-restore --configuration Debug /p:WarningsAsErrors=nullable /p:TargetOS=${{ matrix.targetOS }}
      - name: Build Tools
        run: dotnet build --no-restore --configuration Tools /p:WarningsAsErrors=nullable /p:TargetOS=${{ matrix.targetOS }}
      - name: Build Release
        run: dotnet build --no-restore --configuration Release /p:WarningsAsErrors=nullable /p:TargetOS=${{ matrix.targetOS }}

  cross-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Parse version
        id: parse_version
        shell: pwsh
        run: |
          $ver = [regex]::Match($env:GITHUB_REF, "refs/tags/v?(.+)").Groups[1].Value
          echo ("::set-output name=version::{0}" -f $ver)

      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 10.0.x

      - name: Package client
        run: Tools/package_client_build.py
