name: Publish Client Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Parse version
        id: parse_version
        shell: pwsh
        run: |
          $ver = [regex]::Match($env:GITHUB_REF, "refs/tags/v?(.+)").Groups[1].Value
          echo ("::set-output name=version::{0}" -f $ver)

      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 10.0.x

      - name: Package client
        run: Tools/package_client_build.py

      - name: Shuffle files around
        run: |
          mkdir "release/${{ steps.parse_version.outputs.version }}"
          mv release/*.zip "release/${{ steps.parse_version.outputs.version }}"

      - name: Publish to Robust.Cdn (multi-request)
        run: |
          python3 Tools/publish_client_multi_request.py \
            --cdn-url "https://cdn.luaworld.ru/" \
            --fork "robust" \
            --version "${{ steps.parse_version.outputs.version }}" \
            --engine-version "${{ steps.parse_version.outputs.version }}" \
            --dir "release/${{ steps.parse_version.outputs.version }}"
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
