using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Robust.Client.MapEditor.Interface;

[GenerateTypedNameReferences]
internal sealed partial class MapEditorLayout : Control
{
    public MapEditorLayout()
    {
        RobustXamlLoader.Load(this);
    }
}
