using Robust.Client.AutoGenerated;
using Robust.Client.Editor.Interface;
using Robust.Client.MapEditor.Interface.Panels;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Log;

namespace Robust.Client.MapEditor.Interface;

[GenerateTypedNameReferences]
internal sealed partial class MapEditorLayout : EditorPanel
{
    private readonly ClientMapEditorSystem _mapEditor;
    [Dependency] private readonly IEntityManager _entityManager = null!;

    private readonly MapEditorInnerScope _scope = new();

    internal readonly EntityUid MapData;

    public MapEditorLayout(ISawmill sawmill, ClientMapEditorSystem mapEditor, EntityUid mapData)
    {
        _mapEditor = mapEditor;
        MapData = mapData;
        IoCManager.InjectDependencies(this);

        RobustXamlLoader.Load(this);

        Title = _entityManager.GetComponent<MetaDataComponent>(mapData).EntityName;

        var viewportPanel = new MapEditorViewportPanel(sawmill, _entityManager, mapEditor, mapData)
        {
            Scope = _scope
        };

        Docker.Scope = _scope;
        Docker.AddPanel(viewportPanel);

        var outliner = new MapEditorOutlinerPanel { Scope = _scope };
        var inspector = new MapEditorInspectorPanel { Scope = _scope };
        var activeTool = new ActiveToolPanel(mapEditor, mapData);
        Docker.AddPanelRelative(outliner, viewportPanel.CurrentParent!, DockRelative.Left);
        Docker.AddPanelRelative(new EntityPickerPanel(mapData), outliner.CurrentParent!, DockRelative.Down);
        Docker.AddPanelRelative(inspector, viewportPanel.CurrentParent!, DockRelative.Right);
        Docker.AddPanelRelative(activeTool, inspector.CurrentParent!, DockRelative.Down);
        Docker.AddPanelRelative(new ToolHistoryPanel(mapEditor, mapData), activeTool.CurrentParent!, DockRelative.Down);
    }
}
