using System.Collections.Generic;
using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.Editor.Styling;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Stylesheets;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Log;

namespace Robust.Client.MapEditor.Interface;

[GenerateTypedNameReferences]
internal sealed partial class MapEditorMain : Control
{
    [Dependency] private readonly IEngineStylesheetManager _stylesheetManager = null!;
    [Dependency] private readonly ILogManager _logManager = null!;
    [Dependency] private readonly IFileDialogManager _fileDialog = null!;
    [Dependency] private readonly MapFileHandleManager _fileHandleManager = null!;

    private readonly ClientMapEditorSystem _editorSystem;
    private readonly ISawmill _sawmill;

    private readonly List<MapEditorLayout> _openEditors = [];
    private readonly MapEditorFilePanelScope _scope = new();

    public MapEditorMain(ClientMapEditorSystem editorSystem)
    {
        _editorSystem = editorSystem;
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        FileDocker.AdditionalStyleClasses = [BaseEditorStylesheet.StyleClassEditorDockerLarge];
        FileDocker.Scope = _scope;

        MenuBar.Menus.Add(new MenuBar.Menu
        {
            Title = "File",
            Entries =
            {
                new MenuBar.MenuButton
                {
                    Text = "New",
                    OnPressed = NewFilePressed
                },
                new MenuBar.MenuSeparator(),
                new MenuBar.MenuButton
                {
                    Text = "Open...",
                },
                new MenuBar.MenuSeparator(),
                new MenuBar.MenuButton
                {
                    Text = "Save",
                    OnPressed = SaveFilePressed
                },
                new MenuBar.MenuButton
                {
                    Text = "Save All",
                },
                new MenuBar.MenuButton
                {
                    Text = "Save As",
                }
            }
        });

        MenuBar.Menus.Add(new MenuBar.Menu
        {
            Title = "Edit",
            Entries =
            {
                new MenuBar.MenuButton
                {
                    Text = "Undo",
                },
                new MenuBar.MenuButton
                {
                    Text = "Redo",
                }
            }
        });

        NewFileButton.OnPressed += _ => NewFilePressed();

        editorSystem.OpenMapsUpdated += EditorSystemOnOpenMapsUpdated;

        _sawmill = _logManager.GetSawmill("map_editor.ui.main");
    }

    public void Shutdown()
    {
        _editorSystem.OpenMapsUpdated -= EditorSystemOnOpenMapsUpdated;
    }

    private void EditorSystemOnOpenMapsUpdated(IEnumerable<EntityUid> newMaps)
    {
        var mapsWeHave = _openEditors.Select(x => x.MapData).ToHashSet();
        var mapsWeNeed = newMaps.ToHashSet();

        var removeMaps = mapsWeHave.Except(mapsWeNeed);
        var addedMaps = mapsWeNeed.Except(mapsWeHave);

        foreach (var removeMap in removeMaps)
        {
            var editor = _openEditors.Single(x => x.MapData == removeMap);

            _sawmill.Debug($"Removing editor for map {editor.MapData}");

            _openEditors.Remove(editor);

            editor.CurrentParent?.RemovePanel(editor);
        }

        foreach (var addedMap in addedMaps)
        {
            var layout = new MapEditorLayout(_sawmill, _editorSystem, addedMap)
            {
                Scope = _scope
            };

            _sawmill.Debug($"Adding editor for map {addedMap}");

            _openEditors.Add(layout);

            FileDocker.AddPanel(layout);
        }
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _stylesheetManager.UseStylesheet(this, sa => sa.GetEditorDark());
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _stylesheetManager.StopStylesheet(this);
    }

    private void NewFilePressed()
    {
        _editorSystem.RequestNewFile();
    }

    private async void SaveFilePressed()
    {
        if (GetFocusedEditor() is not { } focusedEditor)
            return;

        var map = focusedEditor.MapData;
        string? newName = null;
        if (!_editorSystem.CheckHasMapFileHandle(map, out var handle))
        {
            // Prompt user for save destination...
            var openResult = await _fileHandleManager.SaveFile();
            if (openResult == null)
                return; // User cancelled.

            handle = openResult.Value.Handle;
            newName = openResult.Value.FileResult.FileName;
        }

        _editorSystem.RequestSaveFile(map, handle, newName);
    }

    private MapEditorLayout? GetFocusedEditor()
    {
        return FileDocker.GetAllPanels().OfType<MapEditorLayout>().SingleOrDefault(l => l.VisibleInTree);
    }
}
